# Generated by Django 4.0.3 on 2022-03-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rank',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
